fix sampler's bug
ShiqiYu/OpenGait pull request #55
Opened 2022-04-15 08:05 UTC by wj1tr0y

When len(obj_list) < k, there will be insufficient candidates for the old behavior. It may be the reason for #53.
For example, if we set batch-size to 32x16 and each person only has 5 sequences, the sample_indices would be 32x5 when applying the old sampler.

2022-04-15 15:05 UTC, darkliang requested changes

2022-04-15 15:05 UTC, darkliang commented on opengait/modeling/losses/triplet.py
>          return ap_dist, an_dist
The new return value has a different shape than the previous version `[p,-1]`

2022-04-16 11:41 UTC, wj1tr0y commented on opengait/data/sampler.py
> +        random.shuffle(idx)
yup, already updated

2022-04-16 11:42 UTC, wj1tr0y commented on opengait/modeling/losses/triplet.py
>          return ap_dist, an_dist
already fixed it in the new version

2022-04-16 11:43 UTC, wj1tr0y commented
I rebased some commits for clarity

2022-04-16 11:52 UTC, ChaoFan996 commented
Awesome PR!
As you mentioned, the mask indexing is faster but may give rise to a data alignment problem in some cases.
I think set replace to True can fix this hidden issue.
However, the implementation of the torch. where can avoid it fundamentally.
We need a trade-off, or someone tells us whether operation (replace=True/False for the sampler in various cases) is better for the final performance.

2022-04-16 15:24 UTC, wj1tr0y commented
> Awesome PR!
> As you mentioned, the mask indexing is faster but may give rise to a data alignment problem in some cases.
> I think set replace to True can fix this hidden issue.
> However, the implementation of the torch. where can avoid it fundamentally.
> We need a trade-off, or someone tells us whether operation (replace=True/False for the sampler in various cases) is better for the final performance.

In my implementation, the behavior of sampler is not changed when there is sufficient sequences but the old one yeilds

2022-04-17 12:21 UTC, darkliang approved these changes

2022-04-17 12:56 UTC, merged

2022-04-17 12:57 UTC, darkliang commented
Thanks for your contribution!